# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/floating_window_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(280, 109)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Graphics/graphics/skypewifi.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWindowOpacity(0.9)
        Dialog.setStyleSheet("QDialog{\n"
"    background-color:rgb(50, 50, 50);\n"
"}\n"
"QLabel{\n"
"    font: 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.gridLayout_5 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.name_widget = QtWidgets.QWidget(Dialog)
        self.name_widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.name_widget.setObjectName("name_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.name_widget)
        self.gridLayout_4.setContentsMargins(9, 0, 9, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.close_btn = QtWidgets.QToolButton(self.name_widget)
        self.close_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.close_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.close_btn.setStyleSheet("QToolButton{\n"
"background-color: transparent;\n"
"border-radius:5px;\n"
"padding:2px;\n"
"}\n"
"QToolButton:hover{\n"
"    \n"
"    background-color: red;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Graphics/graphics/pss_close_nor.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close_btn.setIcon(icon1)
        self.close_btn.setIconSize(QtCore.QSize(30, 30))
        self.close_btn.setObjectName("close_btn")
        self.gridLayout_4.addWidget(self.close_btn, 0, 4, 1, 1)
        self.max_btn = QtWidgets.QToolButton(self.name_widget)
        self.max_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.max_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.max_btn.setStyleSheet("QToolButton{\n"
"background-color: transparent;\n"
"border-radius:5px;\n"
"padding:2px;\n"
"}\n"
"QToolButton:hover{\n"
"    \n"
"    background-color: rgb(0, 200, 255);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Graphics/graphics/topbar_floating_button_maximize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.max_btn.setIcon(icon2)
        self.max_btn.setIconSize(QtCore.QSize(40, 40))
        self.max_btn.setObjectName("max_btn")
        self.gridLayout_4.addWidget(self.max_btn, 0, 3, 1, 1)
        self.user_welcome = QtWidgets.QLabel(self.name_widget)
        self.user_welcome.setStyleSheet("font: bold 10pt \"Segoe UI\";")
        self.user_welcome.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.user_welcome.setScaledContents(True)
        self.user_welcome.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.user_welcome.setWordWrap(False)
        self.user_welcome.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.user_welcome.setObjectName("user_welcome")
        self.gridLayout_4.addWidget(self.user_welcome, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.name_widget)
        self.label.setMinimumSize(QtCore.QSize(20, 20))
        self.label.setMaximumSize(QtCore.QSize(20, 20))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Graphics/graphics/passw.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.name_widget, 0, 0, 1, 4)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.items_widget = QtWidgets.QWidget(self.widget)
        self.items_widget.setStyleSheet("QScrollBar:horizontal\n"
"{\n"
"    height: 15px;\n"
"    margin: 3px 15px 3px 15px;\n"
"    border: 1px transparent #2A2929;\n"
"    border-radius: 4px;\n"
"    background-color: #2A2929;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"    background-color: #605F5F;\n"
"    min-width: 5px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"    margin: 0px 3px 0px 3px;\n"
"    border-image: url(:/qss_icons/rc/right_arrow_disabled.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"    margin: 0px 3px 0px 3px;\n"
"    border-image: url(:/qss_icons/rc/left_arrow_disabled.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover,QScrollBar::add-line:horizontal:on\n"
"{\n"
"    border-image: url(:/qss_icons/rc/right_arrow.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal:hover, QScrollBar::sub-line:horizontal:on\n"
"{\n"
"    border-image: url(:/qss_icons/rc/left_arrow.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"    position:left;\n"
"    background-color: #2A2929;\n"
"    width: 15px;\n"
"    margin: 15px 3px 15px 3px;\n"
"    border: 1px transparent #2A2929;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background-color: #605F5F;\n"
"    min-height: 5px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    margin: 3px 0px 3px 0px;\n"
"    border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    margin: 3px 0px 3px 0px;\n"
"    border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
"{\n"
"\n"
"    border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
"{\n"
"    border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"    background: none;\n"
"}")
        self.items_widget.setObjectName("items_widget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.items_widget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.ntw_status = QtWidgets.QLabel(self.items_widget)
        self.ntw_status.setMinimumSize(QtCore.QSize(30, 30))
        self.ntw_status.setMaximumSize(QtCore.QSize(30, 30))
        self.ntw_status.setText("")
        self.ntw_status.setPixmap(QtGui.QPixmap(":/Graphics/graphics/not_connected.png"))
        self.ntw_status.setScaledContents(True)
        self.ntw_status.setObjectName("ntw_status")
        self.gridLayout_10.addWidget(self.ntw_status, 0, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.items_widget)
        self.scrollArea.setMinimumSize(QtCore.QSize(150, 0))
        self.scrollArea.setStyleSheet("background:transparent;\n"
"border:none;")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 187, 108))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.img_time = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.img_time.setMinimumSize(QtCore.QSize(30, 30))
        self.img_time.setMaximumSize(QtCore.QSize(30, 30))
        self.img_time.setAcceptDrops(False)
        self.img_time.setStyleSheet("QToolButton{\n"
"border:none;\n"
"border-radius: 8px;\n"
"background-color:transparent;\n"
"}\n"
"\n"
"QToolButton::hover{\n"
"    background-color: rgb(20, 20, 20);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Graphics/graphics/connected_time.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.img_time.setIcon(icon3)
        self.img_time.setIconSize(QtCore.QSize(40, 40))
        self.img_time.setAutoRaise(False)
        self.img_time.setObjectName("img_time")
        self.gridLayout_2.addWidget(self.img_time, 0, 0, 1, 1)
        self.connected_time = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.connected_time.setObjectName("connected_time")
        self.gridLayout_2.addWidget(self.connected_time, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.img_speed = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img_speed.setMinimumSize(QtCore.QSize(30, 30))
        self.img_speed.setMaximumSize(QtCore.QSize(30, 30))
        self.img_speed.setText("")
        self.img_speed.setPixmap(QtGui.QPixmap(":/Graphics/graphics/speed_flat.png"))
        self.img_speed.setScaledContents(True)
        self.img_speed.setObjectName("img_speed")
        self.gridLayout_7.addWidget(self.img_speed, 0, 0, 1, 1)
        self.speed_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.speed_widget.setObjectName("speed_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.speed_widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.download = QtWidgets.QLabel(self.speed_widget)
        self.download.setObjectName("download")
        self.gridLayout.addWidget(self.download, 0, 1, 1, 1)
        self.upload = QtWidgets.QLabel(self.speed_widget)
        self.upload.setObjectName("upload")
        self.gridLayout.addWidget(self.upload, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_7.addWidget(self.speed_widget, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setMinimumSize(QtCore.QSize(30, 30))
        self.label_2.setMaximumSize(QtCore.QSize(30, 30))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Graphics/graphics/up_down.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 0, 0, 1, 1)
        self.up_down_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.up_down_widget.setObjectName("up_down_widget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.up_down_widget)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setHorizontalSpacing(10)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.downloaded = QtWidgets.QLabel(self.up_down_widget)
        self.downloaded.setObjectName("downloaded")
        self.gridLayout_8.addWidget(self.downloaded, 0, 3, 1, 1)
        self.uploaded = QtWidgets.QLabel(self.up_down_widget)
        self.uploaded.setObjectName("uploaded")
        self.gridLayout_8.addWidget(self.uploaded, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 0, 4, 1, 1)
        self.gridLayout_9.addWidget(self.up_down_widget, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_9, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_10.addWidget(self.scrollArea, 0, 0, 2, 1)
        self.internet_status = QtWidgets.QLabel(self.items_widget)
        self.internet_status.setMinimumSize(QtCore.QSize(30, 30))
        self.internet_status.setMaximumSize(QtCore.QSize(30, 30))
        self.internet_status.setText("")
        self.internet_status.setPixmap(QtGui.QPixmap(":/Graphics/graphics/critical.png"))
        self.internet_status.setScaledContents(True)
        self.internet_status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.internet_status.setObjectName("internet_status")
        self.gridLayout_10.addWidget(self.internet_status, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.items_widget, 0, 0, 1, 1)
        self.control_widget = QtWidgets.QWidget(self.widget)
        self.control_widget.setObjectName("control_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.control_widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_6.addWidget(self.control_widget, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.widget, 1, 0, 1, 4)

        self.retranslateUi(Dialog)
        self.max_btn.clicked.connect(Dialog.hide)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "XGAMES [Ventana flotante]"))
        self.close_btn.setToolTip(_translate("Dialog", "Cerrar ventana"))
        self.close_btn.setText(_translate("Dialog", "..."))
        self.max_btn.setToolTip(_translate("Dialog", "Cambiar a la ventana principal"))
        self.max_btn.setText(_translate("Dialog", "..."))
        self.user_welcome.setText(_translate("Dialog", "No está loggeado"))
        self.ntw_status.setToolTip(_translate("Dialog", "No se ha detectado red disponible"))
        self.img_time.setToolTip(_translate("Dialog", "Presione para mostrar el tiempo restante/transcurrido"))
        self.img_time.setText(_translate("Dialog", "..."))
        self.connected_time.setToolTip(_translate("Dialog", "Tiempo de conexión"))
        self.connected_time.setText(_translate("Dialog", "00:00:00"))
        self.download.setToolTip(_translate("Dialog", "Velocidad de descarga"))
        self.download.setText(_translate("Dialog", "↓0 B"))
        self.upload.setToolTip(_translate("Dialog", "Velocidad de subida"))
        self.upload.setText(_translate("Dialog", "↑0 B"))
        self.downloaded.setToolTip(_translate("Dialog", "Datos descargados"))
        self.downloaded.setText(_translate("Dialog", "↓0 B"))
        self.uploaded.setToolTip(_translate("Dialog", "Datos subidos"))
        self.uploaded.setText(_translate("Dialog", "↑0 B"))
        self.internet_status.setToolTip(_translate("Dialog", "Aún no se ha loggeado"))
import ui.file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
