# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 430)
        MainWindow.setMinimumSize(QtCore.QSize(600, 430))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/graphics/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow{\n"
"color: rgb(200, 200, 200);\n"
"background-color: rgb(50, 50, 50);/* rgb(10, 10, 10);*/\n"
"}\n"
"\n"
"QMenuBar\n"
"{\n"
"    background-color: #31363b;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background: rgb(124, 124, 124);\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    background-color: rgb(255, 247, 0);\n"
"    color: black;\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"QMenu\n"
"{\n"
"    border: none;\n"
"    background-color: rgb(86, 86, 86);\n"
"    color: rgb(230, 230, 230);\n"
"}\n"
"\n"
"QMenu::icon\n"
"{\n"
"    margin: 5px;\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    padding: 5px 30px 5px 30px;\n"
"    /*border: 1px solid transparent;  reserve space for selection border */\n"
"}\n"
"QMenu::item:hover\n"
"{\n"
"    background-color: rgb(104, 104, 104);\n"
"}\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: rgb(63, 63, 63);\n"
"    color: rgb(217, 217, 217);\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height:1px;\n"
"    background: rgb(255, 255, 255, 80);\n"
"}\n"
"\n"
"QMenu::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"\n"
"/* non-exclusive indicator = check box style indicator\n"
"   (see QActionGroup::setExclusive) */\n"
"QMenu::indicator:non-exclusive:unchecked {\n"
"    image: url(:/qss_icons/rc/checkbox_unchecked.png);\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:unchecked:selected {\n"
"    image: url(:/qss_icons/rc/checkbox_unchecked_disabled.png);\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked {\n"
"    image: url(:/qss_icons/rc/checkbox_checked.png);\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked:selected {\n"
"    image: url(:/qss_icons/rc/checkbox_checked_disabled.png);\n"
"}\n"
"\n"
"/* exclusive indicator = radio button style indicator (see QActionGroup::setExclusive) */\n"
"QMenu::indicator:exclusive:unchecked {\n"
"    image: url(:/qss_icons/rc/radio_unchecked.png);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:unchecked:selected {\n"
"    image: url(:/qss_icons/rc/radio_unchecked_disabled.png);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked {\n"
"    image: url(:/qss_icons/rc/radio_checked.png);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked:selected {\n"
"    image: url(:/qss_icons/rc/radio_checked_disabled.png);\n"
"}\n"
"\n"
"QMenu::right-arrow {\n"
"    margin: 5px;\n"
"    height:10px;\n"
"    width:10px;\n"
"    image: url(:/Resources/resources/rightanglearrow.png);\n"
"    /*image: url(:/Resources/resources/remote_right_arrow_icon.png);*/\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        from ui.QAnimatedStackedWidget import QAnimatedStackedWidget
        self.stackedWidget = QAnimatedStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 11pt \"Segoe UI\";\n"
"}\n"
"QGroupBox {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 11pt \"Segoe UI\";\n"
"    border:1px solid #76797C;\n"
"    border-radius: 2px;\n"
"    margin-top: 20px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QCheckBox, QRadioButton{\n"
"font: 11pt \"Segoe UI\";\n"
"    color: white;\n"
"}\n"
"QCheckBox::indicator, QRadioButton::indicator {\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"QCheckBox::indicator:checked, QRadioButton::indicator:checked {\n"
"    border: 1px solid rgb(255, 205, 0);\n"
"    background-color: rgb(255, 255, 0);\n"
"}\n"
"\n"
"QLineEdit {\n"
"font: 11pt \"Segoe UI\";\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 15px;\n"
"    padding: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    /*color: rgb(100, 100, 100);*/\n"
"    \n"
"    color: rgb(235, 235, 235);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 207, 0);    \n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    font: 12pt \"Calibri\";\n"
"    background-color: rgb(161, 161, 161);\n"
"    border-radius:12px;\n"
"    border:none;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    selection-background-color: rgb(62, 62, 62);\n"
"    min-width: 75px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QComboBox:drop-down {\n"
"    color: white;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 12px;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QComboBox:down-arrow {\n"
"   \n"
"    image: url(:/Resources/resources/arrow_down.png);\n"
"    height: 12px;\n"
"    width: 12px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QComboBox:on:hover:focus {\n"
"   \n"
"    image: url(:/Resources/resources/arrow_down_disabled.png);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    color: white;\n"
"    background-color: #232629;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    selection-background-color: #18465d;\n"
"}\n"
"\n"
"QPushButton {    \n"
"    color: rgb(222, 222, 222);\n"
"    font: bold 12pt \"Calibri\";\n"
"    background-color: rgb(80, 80, 80);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 10px;\n"
"    padding:5px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.page_3)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.mikrotic_ip = QtWidgets.QLineEdit(self.widget_3)
        self.mikrotic_ip.setClearButtonEnabled(True)
        self.mikrotic_ip.setObjectName("mikrotic_ip")
        self.gridLayout_5.addWidget(self.mikrotic_ip, 0, 1, 1, 1)
        self.network_adapter = QtWidgets.QComboBox(self.widget_3)
        self.network_adapter.setObjectName("network_adapter")
        self.gridLayout_5.addWidget(self.network_adapter, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_3, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.page_3)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.RestoreDefaults|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_4.addWidget(self.buttonBox, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 2, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.page_3)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.widget_5)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 26pt \"Segoe UI\";\n"
"color: rgb(188, 188, 188);")
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.go_back = QtWidgets.QToolButton(self.widget_5)
        self.go_back.setMinimumSize(QtCore.QSize(50, 50))
        self.go_back.setStyleSheet("QToolButton{\n"
"    background-color: transparent;\n"
"    border-radius: 25px;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: rgb(90, 90, 90);\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Graphics/graphics/back.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.go_back.setIcon(icon1)
        self.go_back.setIconSize(QtCore.QSize(40, 40))
        self.go_back.setObjectName("go_back")
        self.gridLayout_6.addWidget(self.go_back, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.widget_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.login_area = QtWidgets.QFrame(self.page)
        self.login_area.setMaximumSize(QtCore.QSize(450, 550))
        self.login_area.setStyleSheet("border-radius: 10px;")
        self.login_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.login_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_area.setObjectName("login_area")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.login_area)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.logo = QtWidgets.QLabel(self.login_area)
        self.logo.setMinimumSize(QtCore.QSize(250, 60))
        self.logo.setMaximumSize(QtCore.QSize(360, 110))
        self.logo.setStyleSheet("/*background-image: url(:/Logo/graphics/xgames5.png);*/\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/Logo/graphics/xgames5.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logo.setObjectName("logo")
        self.verticalLayout_3.addWidget(self.logo)
        self.user_ledit = QtWidgets.QLineEdit(self.login_area)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.user_ledit.setFont(font)
        self.user_ledit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 15px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 207, 0);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.user_ledit.setMaxLength(32)
        self.user_ledit.setClearButtonEnabled(True)
        self.user_ledit.setObjectName("user_ledit")
        self.verticalLayout_3.addWidget(self.user_ledit)
        self.password_ledit = QtWidgets.QLineEdit(self.login_area)
        self.password_ledit.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.password_ledit.setFont(font)
        self.password_ledit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 15px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 207, 0);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.password_ledit.setMaxLength(16)
        self.password_ledit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_ledit.setReadOnly(False)
        self.password_ledit.setClearButtonEnabled(True)
        self.password_ledit.setObjectName("password_ledit")
        self.verticalLayout_3.addWidget(self.password_ledit)
        self.widget = QtWidgets.QWidget(self.login_area)
        self.widget.setStyleSheet("QCheckBox, QRadioButton{\n"
"font: 10pt \"Segoe UI\";\n"
"    color: rgb(218, 218, 218);\n"
"}\n"
"QCheckBox::indicator, QRadioButton::indicator {\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"QCheckBox::indicator:checked, QRadioButton::indicator:checked {\n"
"    border: 1px solid rgb(255, 205, 0);\n"
"    background-color: rgb(255, 255, 0);\n"
"}")
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_save_user = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.checkBox_save_user.setFont(font)
        self.checkBox_save_user.setStyleSheet("")
        self.checkBox_save_user.setChecked(True)
        self.checkBox_save_user.setObjectName("checkBox_save_user")
        self.gridLayout_3.addWidget(self.checkBox_save_user, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        self.permanent_rb = QtWidgets.QRadioButton(self.widget)
        self.permanent_rb.setChecked(False)
        self.permanent_rb.setObjectName("permanent_rb")
        self.gridLayout_3.addWidget(self.permanent_rb, 0, 3, 1, 1)
        self.ticket_rb = QtWidgets.QRadioButton(self.widget)
        self.ticket_rb.setChecked(True)
        self.ticket_rb.setObjectName("ticket_rb")
        self.gridLayout_3.addWidget(self.ticket_rb, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.widget)
        self.login_btn = QtWidgets.QPushButton(self.login_area)
        self.login_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.login_btn.setStyleSheet("QPushButton {    \n"
"    \n"
"    color: rgb(222, 222, 222);\n"
"    font: bold 12pt \"Calibri\";\n"
"    background-color: rgb(80, 80, 80);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Graphics/graphics/ic_lock_open_wht_24dp.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.login_btn.setIcon(icon2)
        self.login_btn.setIconSize(QtCore.QSize(30, 30))
        self.login_btn.setObjectName("login_btn")
        self.verticalLayout_3.addWidget(self.login_btn)
        self.gridLayout_2.addWidget(self.login_area, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.status_container = QtWidgets.QWidget(self.page_2)
        self.status_container.setStyleSheet("QScrollBar:horizontal\n"
"{\n"
"    height: 15px;\n"
"    margin: 3px 15px 3px 15px;\n"
"    border: 1px transparent #2A2929;\n"
"    border-radius: 4px;\n"
"    background-color: #2A2929;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"    background-color: #605F5F;\n"
"    min-width: 5px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"    margin: 0px 3px 0px 3px;\n"
"    border-image: url(:/qss_icons/rc/right_arrow_disabled.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"    margin: 0px 3px 0px 3px;\n"
"    border-image: url(:/qss_icons/rc/left_arrow_disabled.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover,QScrollBar::add-line:horizontal:on\n"
"{\n"
"    border-image: url(:/qss_icons/rc/right_arrow.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal:hover, QScrollBar::sub-line:horizontal:on\n"
"{\n"
"    border-image: url(:/qss_icons/rc/left_arrow.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"    background-color: #2A2929;\n"
"    width: 15px;\n"
"    margin: 15px 3px 15px 3px;\n"
"    border: 1px transparent #2A2929;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background-color: #605F5F;\n"
"    min-height: 5px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    margin: 3px 0px 3px 0px;\n"
"    border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    margin: 3px 0px 3px 0px;\n"
"    border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
"{\n"
"\n"
"    border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
"{\n"
"    border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"    background: none;\n"
"}")
        self.status_container.setObjectName("status_container")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.status_container)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem2, 2, 0, 1, 2)
        self.widget_4 = QtWidgets.QWidget(self.status_container)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_13.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.logout_btn = QtWidgets.QPushButton(self.widget_4)
        self.logout_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.logout_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.logout_btn.setStyleSheet("QPushButton {    \n"
"    \n"
"    color: rgb(222, 222, 222);\n"
"    font: bold 12pt \"Calibri\";\n"
"    background-color: rgb(80, 80, 80);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Graphics/graphics/ic_lock_power_off_alpha.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.logout_btn.setIcon(icon3)
        self.logout_btn.setIconSize(QtCore.QSize(30, 30))
        self.logout_btn.setObjectName("logout_btn")
        self.gridLayout_13.addWidget(self.logout_btn, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.widget_4, 3, 0, 1, 2)
        self.widget_2 = QtWidgets.QWidget(self.status_container)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.gridLayout_14.addWidget(self.widget_2, 1, 0, 1, 2)
        self.scrollArea = QtWidgets.QScrollArea(self.status_container)
        self.scrollArea.setStyleSheet("background:transparent;\n"
"border:none;")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 462, 298))
        self.scrollAreaWidgetContents_2.setStyleSheet("")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.time_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.time_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.time_widget.setMaximumSize(QtCore.QSize(16777215, 110))
        self.time_widget.setStyleSheet("QWidget#time_widget{\n"
"    background-color: rgb(3, 213, 255);\n"
"}\n"
"\n"
"QWidget#time_widget::hover{\n"
"    background-color: rgb(2, 192, 230);\n"
"}")
        self.time_widget.setObjectName("time_widget")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.time_widget)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_3 = QtWidgets.QLabel(self.time_widget)
        self.label_3.setMinimumSize(QtCore.QSize(50, 50))
        self.label_3.setMaximumSize(QtCore.QSize(50, 50))
        self.label_3.setStyleSheet("font: 20pt \"Segoe UI\";")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Graphics/graphics/connected_time.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_20.addWidget(self.label_3, 0, 0, 1, 1)
        self.time_content_2 = QtWidgets.QWidget(self.time_widget)
        self.time_content_2.setObjectName("time_content_2")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.time_content_2)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.time_percent = QtWidgets.QLabel(self.time_content_2)
        self.time_percent.setStyleSheet("font: bold 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);")
        self.time_percent.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.time_percent.setObjectName("time_percent")
        self.gridLayout_21.addWidget(self.time_percent, 3, 0, 1, 1)
        self.current_time = QtWidgets.QLabel(self.time_content_2)
        self.current_time.setStyleSheet("font: bold 16pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.current_time.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.current_time.setObjectName("current_time")
        self.gridLayout_21.addWidget(self.current_time, 0, 0, 1, 1)
        self.elapsed_time = QtWidgets.QLabel(self.time_content_2)
        self.elapsed_time.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);")
        self.elapsed_time.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.elapsed_time.setObjectName("elapsed_time")
        self.gridLayout_21.addWidget(self.elapsed_time, 1, 0, 1, 1)
        self.gridLayout_20.addWidget(self.time_content_2, 0, 1, 1, 1)
        self.time_progress = QtWidgets.QProgressBar(self.time_widget)
        self.time_progress.setMaximumSize(QtCore.QSize(16777215, 5))
        self.time_progress.setStyleSheet("QProgressBar {\n"
"    border: none;\n"
"    /*border-radius: 1px;\n"
"    text-align: center;*/\n"
"    background-color: rgb(0, 0, 0, 100);\n"
"    height:1px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border-radius: 0.5px;\n"
"    background-color: white;\n"
"}")
        self.time_progress.setProperty("value", 50)
        self.time_progress.setTextVisible(False)
        self.time_progress.setObjectName("time_progress")
        self.gridLayout_20.addWidget(self.time_progress, 1, 0, 1, 2)
        self.gridLayout_34.addWidget(self.time_widget, 0, 0, 1, 1)
        self.welcome_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.welcome_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.welcome_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.welcome_widget.setStyleSheet("QWidget#welcome_widget{\n"
"    background-color:  rgb(38, 175, 0);\n"
"}\n"
"\n"
"QWidget#welcome_widget::hover{\n"
"    background-color:green ;\n"
"}")
        self.welcome_widget.setObjectName("welcome_widget")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.welcome_widget)
        self.gridLayout_22.setContentsMargins(-1, 50, -1, 50)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.user_2 = QtWidgets.QLabel(self.welcome_widget)
        self.user_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: bold 12pt \"Segoe UI\";")
        self.user_2.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.user_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.user_2.setWordWrap(True)
        self.user_2.setObjectName("user_2")
        self.gridLayout_22.addWidget(self.user_2, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4 = QtWidgets.QLabel(self.welcome_widget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setMaximumSize(QtCore.QSize(150, 50))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/Logo/graphics/xgames_white.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_22.addWidget(self.label_4, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.gridLayout_34.addWidget(self.welcome_widget, 0, 1, 2, 1)
        self.speed_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.speed_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.speed_widget.setMaximumSize(QtCore.QSize(166662, 110))
        self.speed_widget.setStyleSheet("QWidget#speed_widget{\n"
"    background-color:rgb(255, 152, 166);\n"
"}\n"
"\n"
"QWidget#speed_widget::hover{\n"
"    background-color:rgb(232, 138, 152);\n"
"}")
        self.speed_widget.setObjectName("speed_widget")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.speed_widget)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_7 = QtWidgets.QLabel(self.speed_widget)
        self.label_7.setMinimumSize(QtCore.QSize(50, 50))
        self.label_7.setMaximumSize(QtCore.QSize(50, 50))
        self.label_7.setStyleSheet("font: 20pt \"Segoe UI\";")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/Graphics/graphics/speed_flat.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_23.addWidget(self.label_7, 0, 0, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.speed_widget)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.widget_9)
        self.gridLayout_24.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.widget_10 = QtWidgets.QWidget(self.widget_9)
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.widget_10)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.upload_speed = QtWidgets.QLabel(self.widget_10)
        self.upload_speed.setStyleSheet("font: bold 14pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);")
        self.upload_speed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.upload_speed.setObjectName("upload_speed")
        self.gridLayout_27.addWidget(self.upload_speed, 0, 0, 1, 1)
        self.increase_u_speed = QtWidgets.QLabel(self.widget_10)
        self.increase_u_speed.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);")
        self.increase_u_speed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.increase_u_speed.setObjectName("increase_u_speed")
        self.gridLayout_27.addWidget(self.increase_u_speed, 1, 0, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_27, 0, 0, 1, 1)
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.download_speed = QtWidgets.QLabel(self.widget_10)
        self.download_speed.setStyleSheet("font: bold 14pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);")
        self.download_speed.setObjectName("download_speed")
        self.gridLayout_28.addWidget(self.download_speed, 0, 0, 1, 1)
        self.increase_d_speed = QtWidgets.QLabel(self.widget_10)
        self.increase_d_speed.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);")
        self.increase_d_speed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.increase_d_speed.setObjectName("increase_d_speed")
        self.gridLayout_28.addWidget(self.increase_d_speed, 1, 0, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_28, 0, 1, 1, 1)
        self.gridLayout_24.addWidget(self.widget_10, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.widget_9, 0, 1, 1, 1)
        self.gridLayout_34.addWidget(self.speed_widget, 1, 0, 1, 1)
        self.up_down_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.up_down_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.up_down_widget.setMaximumSize(QtCore.QSize(166662, 110))
        self.up_down_widget.setStyleSheet("QWidget#up_down_widget{\n"
"    background-color:rgb(255, 170, 0);\n"
"}\n"
"\n"
"QWidget#up_down_widget::hover{\n"
"    background-color:rgb(223, 125, 5);\n"
"}")
        self.up_down_widget.setObjectName("up_down_widget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.up_down_widget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_8 = QtWidgets.QLabel(self.up_down_widget)
        self.label_8.setMinimumSize(QtCore.QSize(50, 50))
        self.label_8.setMaximumSize(QtCore.QSize(50, 50))
        self.label_8.setStyleSheet("font: 20pt \"Segoe UI\";")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/Graphics/graphics/up_down.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 0, 0, 1, 1)
        self.widget_12 = QtWidgets.QWidget(self.up_down_widget)
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_12)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.uploaded_data = QtWidgets.QLabel(self.widget_12)
        self.uploaded_data.setStyleSheet("font: bold 14pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);")
        self.uploaded_data.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.uploaded_data.setObjectName("uploaded_data")
        self.gridLayout_9.addWidget(self.uploaded_data, 0, 0, 1, 1)
        self.downloaded_data = QtWidgets.QLabel(self.widget_12)
        self.downloaded_data.setStyleSheet("font: bold 14pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);")
        self.downloaded_data.setObjectName("downloaded_data")
        self.gridLayout_9.addWidget(self.downloaded_data, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.widget_12, 0, 1, 1, 1)
        self.gridLayout_34.addWidget(self.up_down_widget, 2, 0, 1, 1)
        self.tile_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.tile_widget.setStyleSheet("QWidget#tile_widget{\n"
"    background-color:rgb(56, 93, 173);\n"
"}\n"
"\n"
"QWidget#tile_widget::hover{\n"
"    background-color:rgb(20, 70, 110);\n"
"}")
        self.tile_widget.setObjectName("tile_widget")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.tile_widget)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.label_10 = QtWidgets.QLabel(self.tile_widget)
        self.label_10.setMinimumSize(QtCore.QSize(0, 0))
        self.label_10.setMaximumSize(QtCore.QSize(200, 50))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/images/images/jalex.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout_39.addWidget(self.label_10, 0, 0, 1, 1)
        self.gridLayout_34.addWidget(self.tile_widget, 2, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_14.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.status_container, 0, 0, 1, 2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.message = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.message.setFont(font)
        self.message.setStyleSheet("/*font: 26pt \"Segoe UI\";*/\n"
"color: rgba(255, 255, 255, 100);\n"
"padding:30px;\n"
"background: rgba(0, 0, 0, 80);\n"
"border-radius:20px;")
        self.message.setTextFormat(QtCore.Qt.RichText)
        self.message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.message.setObjectName("message")
        self.gridLayout_7.addWidget(self.message, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMinimumSize(QtCore.QSize(0, 30))
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.top_bar.setStyleSheet("")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(20, 5, 20, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_error = QtWidgets.QFrame(self.top_bar)
        self.frame_error.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_error.setStyleSheet("background-color: rgb(255, 85, 127);\n"
"border-radius: 10px;")
        self.frame_error.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error.setObjectName("frame_error")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_error)
        self.horizontalLayout_3.setContentsMargins(10, 3, 10, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_error = QtWidgets.QLabel(self.frame_error)
        self.label_error.setStyleSheet("font: 11pt \"Calibri\";")
        self.label_error.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.horizontalLayout_3.addWidget(self.label_error, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.show_details = QtWidgets.QToolButton(self.frame_error)
        self.show_details.setStyleSheet("QToolButton{\n"
"color: rgb(0, 0, 0);\n"
"font: bold 8pt \"Segoe UI\";\n"
"}\n"
"QToolButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.show_details.setObjectName("show_details")
        self.horizontalLayout_3.addWidget(self.show_details)
        self.close_pupup = QtWidgets.QPushButton(self.frame_error)
        self.close_pupup.setMaximumSize(QtCore.QSize(20, 20))
        self.close_pupup.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;    \n"
"    background-image: url(:/Close_Image/graphics/cil-x.png);\n"
"    background-position: center;    \n"
"    background-color: rgb(60, 60, 60, 150);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 50, 50);    \n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 35, 35);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.close_pupup.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Graphics/graphics/cil-x.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close_pupup.setIcon(icon4)
        self.close_pupup.setObjectName("close_pupup")
        self.horizontalLayout_3.addWidget(self.close_pupup)
        self.horizontalLayout_2.addWidget(self.frame_error)
        self.gridLayout.addWidget(self.top_bar, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        self.menuPrograma = QtWidgets.QMenu(self.menubar)
        self.menuPrograma.setObjectName("menuPrograma")
        self.menuHerramientas = QtWidgets.QMenu(self.menubar)
        self.menuHerramientas.setObjectName("menuHerramientas")
        self.menuAcerca_de = QtWidgets.QMenu(self.menubar)
        self.menuAcerca_de.setObjectName("menuAcerca_de")
        self.developer_telegram = QtWidgets.QMenu(self.menuAcerca_de)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Graphics/graphics/telegram.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.developer_telegram.setIcon(icon5)
        self.developer_telegram.setObjectName("developer_telegram")
        self.donate_menu = QtWidgets.QMenu(self.menubar)
        self.donate_menu.setObjectName("donate_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.exit_action = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Graphics/graphics/highlight_remove@2x.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.exit_action.setIcon(icon6)
        self.exit_action.setObjectName("exit_action")
        self.admin_users_action = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Graphics/graphics/passw.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.admin_users_action.setIcon(icon7)
        self.admin_users_action.setObjectName("admin_users_action")
        self.get_status_action = QtWidgets.QAction(MainWindow)
        self.get_status_action.setObjectName("get_status_action")
        self.developer = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Graphics/graphics/develop.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.developer.setIcon(icon8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.developer.setFont(font)
        self.developer.setObjectName("developer")
        self.show_f_window = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Graphics/graphics/skypewifi.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.show_f_window.setIcon(icon9)
        self.show_f_window.setObjectName("show_f_window")
        self.twitter = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Graphics/graphics/alt_twitter_1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.twitter.setIcon(icon10)
        self.twitter.setObjectName("twitter")
        self.options = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Graphics/graphics/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.options.setIcon(icon11)
        self.options.setObjectName("options")
        self.support = QtWidgets.QAction(MainWindow)
        self.support.setIcon(icon5)
        self.support.setObjectName("support")
        self.about_me = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Graphics/graphics/alt_sms_2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.about_me.setIcon(icon12)
        self.about_me.setObjectName("about_me")
        self.support_2 = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Graphics/graphics/icon_support.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.support_2.setIcon(icon13)
        self.support_2.setObjectName("support_2")
        self.channel = QtWidgets.QAction(MainWindow)
        self.channel.setObjectName("channel")
        self.donate = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Graphics/graphics/Coffee Time.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.donate.setIcon(icon14)
        self.donate.setObjectName("donate")
        self.facebook = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Graphics/graphics/facebook (2).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.facebook.setIcon(icon15)
        self.facebook.setObjectName("facebook")
        self.developer_channel = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/Graphics/graphics/success.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.developer_channel.setIcon(icon16)
        self.developer_channel.setObjectName("developer_channel")
        self.menuPrograma.addAction(self.show_f_window)
        self.menuPrograma.addSeparator()
        self.menuPrograma.addAction(self.exit_action)
        self.menuHerramientas.addAction(self.admin_users_action)
        self.menuHerramientas.addAction(self.options)
        self.developer_telegram.addAction(self.about_me)
        self.developer_telegram.addAction(self.developer_channel)
        self.developer_telegram.addAction(self.support_2)
        self.menuAcerca_de.addAction(self.developer)
        self.menuAcerca_de.addAction(self.facebook)
        self.menuAcerca_de.addAction(self.developer_telegram.menuAction())
        self.menuAcerca_de.addAction(self.twitter)
        self.menuAcerca_de.addSeparator()
        self.donate_menu.addAction(self.donate)
        self.menubar.addAction(self.menuPrograma.menuAction())
        self.menubar.addAction(self.menuHerramientas.menuAction())
        self.menubar.addAction(self.menuAcerca_de.menuAction())
        self.menubar.addAction(self.donate_menu.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.ticket_rb.clicked['bool'].connect(self.password_ledit.setDisabled)
        self.permanent_rb.clicked['bool'].connect(self.password_ledit.setEnabled)
        self.exit_action.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.user_ledit, self.password_ledit)
        MainWindow.setTabOrder(self.password_ledit, self.ticket_rb)
        MainWindow.setTabOrder(self.ticket_rb, self.permanent_rb)
        MainWindow.setTabOrder(self.permanent_rb, self.checkBox_save_user)
        MainWindow.setTabOrder(self.checkBox_save_user, self.login_btn)
        MainWindow.setTabOrder(self.login_btn, self.close_pupup)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "X-GAMES"))
        self.mikrotic_ip.setText(_translate("MainWindow", "192.168.10.1"))
        self.mikrotic_ip.setPlaceholderText(_translate("MainWindow", "Ejemplo: 192.168.10.1"))
        self.label_5.setText(_translate("MainWindow", "Dirección IP del MikroTik"))
        self.label_2.setText(_translate("MainWindow", "Adaptador de red:"))
        self.label.setText(_translate("MainWindow", "Opciones"))
        self.go_back.setText(_translate("MainWindow", "..."))
        self.user_ledit.setPlaceholderText(_translate("MainWindow", "USUARIO"))
        self.password_ledit.setPlaceholderText(_translate("MainWindow", "CONTRASEÑA"))
        self.checkBox_save_user.setText(_translate("MainWindow", "Guardar usuario"))
        self.permanent_rb.setText(_translate("MainWindow", "Fijo"))
        self.ticket_rb.setText(_translate("MainWindow", "Ticket"))
        self.login_btn.setText(_translate("MainWindow", "LOGIN"))
        self.logout_btn.setText(_translate("MainWindow", "LOGOUT"))
        self.time_widget.setToolTip(_translate("MainWindow", "Tiempo"))
        self.time_widget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Muestra el tiempo que ha estado conectado a Internet, el tiempo restante (si es un usuario temporal) y el porciento de consumo del tiempo</p></body></html>"))
        self.time_percent.setText(_translate("MainWindow", "0%"))
        self.current_time.setText(_translate("MainWindow", "00:00:00"))
        self.elapsed_time.setText(_translate("MainWindow", "00:00:00"))
        self.welcome_widget.setToolTip(_translate("MainWindow", "Bienvenido a XGAMES"))
        self.user_2.setText(_translate("MainWindow", "Bienvenido JaleXCode Solutions"))
        self.speed_widget.setToolTip(_translate("MainWindow", "Velocidad de Internet"))
        self.speed_widget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Muestra la velocidad del tráfico de la red correspondiente al adaptador de Red seleccionado</p></body></html>"))
        self.upload_speed.setText(_translate("MainWindow", "↑ 0 KiB"))
        self.increase_u_speed.setText(_translate("MainWindow", "+0 B"))
        self.download_speed.setText(_translate("MainWindow", "↓ 0 KiB"))
        self.increase_d_speed.setText(_translate("MainWindow", "+0 B"))
        self.up_down_widget.setToolTip(_translate("MainWindow", "Cantidad de datos subidos/descargados"))
        self.up_down_widget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Muestra la cantidad de datos enviados o descargados desde que inició sesión</p></body></html>"))
        self.uploaded_data.setText(_translate("MainWindow", "↑ 0 KiB"))
        self.downloaded_data.setText(_translate("MainWindow", "↓ 0 KiB"))
        self.tile_widget.setToolTip(_translate("MainWindow", "POWERED by JaleXCode"))
        self.message.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">Iniciando XGAMES</span></p><p align=\"center\"><span style=\" font-size:20pt;\">Por favor, espere...</span></p></body></html>"))
        self.label_error.setText(_translate("MainWindow", "Error"))
        self.show_details.setText(_translate("MainWindow", "Ver detalles"))
        self.menuPrograma.setTitle(_translate("MainWindow", "Programa"))
        self.menuHerramientas.setTitle(_translate("MainWindow", "Herramientas"))
        self.menuAcerca_de.setTitle(_translate("MainWindow", "Acerca de"))
        self.developer_telegram.setTitle(_translate("MainWindow", "Telegram"))
        self.donate_menu.setTitle(_translate("MainWindow", "Donación"))
        self.exit_action.setText(_translate("MainWindow", "Salir"))
        self.admin_users_action.setText(_translate("MainWindow", "Administrar usuarios"))
        self.get_status_action.setText(_translate("MainWindow", "Obtener estado"))
        self.developer.setText(_translate("MainWindow", "Desarrollado por JalexCode"))
        self.show_f_window.setText(_translate("MainWindow", "Ver ventana de estado"))
        self.twitter.setText(_translate("MainWindow", "Twitter: @javyalejandro99"))
        self.options.setText(_translate("MainWindow", "Opciones"))
        self.support.setText(_translate("MainWindow", "Soporte: @xgamesoporte"))
        self.about_me.setText(_translate("MainWindow", "Desarrollador: @jalexcode"))
        self.support_2.setText(_translate("MainWindow", "Soporte: @xgamesoporte"))
        self.channel.setText(_translate("MainWindow", "Canal: "))
        self.donate.setText(_translate("MainWindow", "Info"))
        self.facebook.setText(_translate("MainWindow", "Facebook: JalexCode Solutions"))
        self.developer_channel.setText(_translate("MainWindow", "Canal del desarrollador: @jalexcodesolutions"))
import ui.file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
