# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QListWidgetItem


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 444)
        MainWindow.setMinimumSize(QtCore.QSize(714, 444))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/skypewifi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow{\n"
"color: rgb(200, 200, 200);\n"
"background-color: rgb(50, 50, 50);/* rgb(10, 10, 10);*/\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.top_bar.setStyleSheet("")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(20, 5, 20, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_error = QtWidgets.QFrame(self.top_bar)
        self.frame_error.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_error.setStyleSheet("background-color: rgb(255, 85, 127);\n"
"border-radius: 10px;")
        self.frame_error.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error.setObjectName("frame_error")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_error)
        self.horizontalLayout_3.setContentsMargins(10, 3, 10, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_error = QtWidgets.QLabel(self.frame_error)
        self.label_error.setStyleSheet("font: 11pt \"Calibri\";")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.horizontalLayout_3.addWidget(self.label_error)
        self.close_pupup = QtWidgets.QPushButton(self.frame_error)
        self.close_pupup.setMaximumSize(QtCore.QSize(20, 20))
        self.close_pupup.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;    \n"
"    background-image: url(:/Close_Image/graphics/cil-x.png);\n"
"    background-position: center;    \n"
"    background-color: rgb(60, 60, 60, 150);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 50, 50);    \n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 35, 35);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.close_pupup.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Graphics/graphics/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_pupup.setIcon(icon1)
        self.close_pupup.setObjectName("close_pupup")
        self.horizontalLayout_3.addWidget(self.close_pupup)
        self.horizontalLayout_2.addWidget(self.frame_error)
        self.gridLayout.addWidget(self.top_bar, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.login_area = QtWidgets.QFrame(self.page)
        self.login_area.setMaximumSize(QtCore.QSize(450, 550))
        self.login_area.setStyleSheet("border-radius: 10px;")
        self.login_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.login_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_area.setObjectName("login_area")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.login_area)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.logo = QtWidgets.QLabel(self.login_area)
        self.logo.setMinimumSize(QtCore.QSize(250, 60))
        self.logo.setMaximumSize(QtCore.QSize(360, 110))
        self.logo.setStyleSheet("/*background-image: url(:/Logo/graphics/xgames5.png);*/\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/Logo/graphics/xgames5.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.verticalLayout_3.addWidget(self.logo)
        self.user_ledit = QtWidgets.QLineEdit(self.login_area)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.user_ledit.setFont(font)
        self.user_ledit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 15px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 207, 0);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.user_ledit.setMaxLength(32)
        self.user_ledit.setClearButtonEnabled(True)
        self.user_ledit.setObjectName("user_ledit")
        self.verticalLayout_3.addWidget(self.user_ledit)
        self.password_ledit = QtWidgets.QLineEdit(self.login_area)
        self.password_ledit.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.password_ledit.setFont(font)
        self.password_ledit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 15px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 207, 0);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.password_ledit.setMaxLength(16)
        self.password_ledit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_ledit.setReadOnly(False)
        self.password_ledit.setClearButtonEnabled(True)
        self.password_ledit.setObjectName("password_ledit")
        self.verticalLayout_3.addWidget(self.password_ledit)
        self.widget = QtWidgets.QWidget(self.login_area)
        self.widget.setStyleSheet("QCheckBox, QRadioButton{\n"
"font: 10pt \"Segoe UI\";\n"
"    color: rgb(218, 218, 218);\n"
"}\n"
"QCheckBox::indicator, QRadioButton::indicator {\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"QCheckBox::indicator:checked, QRadioButton::indicator:checked {\n"
"    border: 1px solid rgb(255, 205, 0);\n"
"    background-color: rgb(255, 255, 0);\n"
"}")
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_save_user = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.checkBox_save_user.setFont(font)
        self.checkBox_save_user.setStyleSheet("")
        self.checkBox_save_user.setChecked(True)
        self.checkBox_save_user.setObjectName("checkBox_save_user")
        self.gridLayout_3.addWidget(self.checkBox_save_user, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.permanent_rb = QtWidgets.QRadioButton(self.widget)
        self.permanent_rb.setChecked(False)
        self.permanent_rb.setObjectName("permanent_rb")
        self.gridLayout_3.addWidget(self.permanent_rb, 0, 3, 1, 1)
        self.ticket_rb = QtWidgets.QRadioButton(self.widget)
        self.ticket_rb.setChecked(True)
        self.ticket_rb.setObjectName("ticket_rb")
        self.gridLayout_3.addWidget(self.ticket_rb, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.widget)
        self.login_btn = QtWidgets.QPushButton(self.login_area)
        self.login_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.login_btn.setStyleSheet("QPushButton {    \n"
"    \n"
"    color: rgb(222, 222, 222);\n"
"    font: bold 12pt \"Calibri\";\n"
"    background-color: rgb(80, 80, 80);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Graphics/graphics/ic_lock_open_wht_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.login_btn.setIcon(icon2)
        self.login_btn.setIconSize(QtCore.QSize(30, 30))
        self.login_btn.setObjectName("login_btn")
        self.verticalLayout_3.addWidget(self.login_btn)
        self.gridLayout_2.addWidget(self.login_area, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.status_container = QtWidgets.QWidget(self.page_2)
        self.status_container.setObjectName("status_container")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.status_container)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.table = QtWidgets.QTableWidget(self.status_container)
        self.table.setStyleSheet("QTableWidget\n"
"{\n"
"    font: 14pt \"Segoe UI\";\n"
"    border: none;/*1px solid #76797C;*/\n"
"    /*gridline-color: transparent;*/\n"
"    background-color: rgb(50, 50, 50);\n"
"}\n"
"\n"
"QTableWidget::item{\n"
"    padding:5px;\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget::item:pressed {\n"
"    background: #18465d;\n"
"   /* color: #eff0f1;*/\n"
"    border:none;\n"
"}\n"
"\n"
"QTableWidget::item:selected:active {\n"
"    background: #287399;\n"
"    /* color: #eff0f1;*/\n"
"    border:none;\n"
"}\n"
"\n"
"QHeaderView\n"
"{\n"
"    background-color: transparent;\n"
"    border: none;/*1px transparent;*/\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"    font: 11pt \"Segoe UI\";\n"
"}\n"
"\n"
"QHeaderView::section  {\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: #eff0f1;\n"
"    padding: 5px;\n"
"     border: none;/*1px solid #76797C;*/\n"
"    text-align: center;\n"
"}\n"
"\n"
"QHeaderView::section:checked\n"
" {\n"
"    color: white;\n"
"    background-color: #334e5e;\n"
" }\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: rgb(40, 40, 40);/*#31363b;*/\n"
"    border: none;/*1px transparent #76797C;*/\n"
"}")
        self.table.setObjectName("table")
        self.table.setColumnCount(2)
        self.table.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(2, 1, item)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setStretchLastSection(False)
        self.gridLayout_12.addWidget(self.table, 1, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.status_container)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_13.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.logout_btn = QtWidgets.QPushButton(self.widget_4)
        self.logout_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.logout_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.logout_btn.setStyleSheet("QPushButton {    \n"
"    \n"
"    color: rgb(222, 222, 222);\n"
"    font: bold 12pt \"Calibri\";\n"
"    background-color: rgb(80, 80, 80);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Graphics/graphics/ic_lock_power_off_alpha.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_btn.setIcon(icon3)
        self.logout_btn.setIconSize(QtCore.QSize(30, 30))
        self.logout_btn.setObjectName("logout_btn")
        self.gridLayout_13.addWidget(self.logout_btn, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_4, 2, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.status_container)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.xgames_btn = QtWidgets.QToolButton(self.widget_2)
        self.xgames_btn.setMinimumSize(QtCore.QSize(190, 108))
        self.xgames_btn.setStyleSheet("QToolButton{\n"
"border:none;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:lightgreen;\n"
"}\n"
"\n"
"QToolButton::hover{\n"
"    background-color:rgb(100, 212, 75);\n"
"}\n"
"\n"
"QToolButton::pressed{\n"
"    background-color:green;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Logo/graphics/xgames_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.xgames_btn.setIcon(icon4)
        self.xgames_btn.setIconSize(QtCore.QSize(150, 80))
        self.xgames_btn.setObjectName("xgames_btn")
        self.gridLayout_16.addWidget(self.xgames_btn, 0, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem1, 0, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem3, 0, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem4, 0, 3, 1, 1)
        self.time_widget = QtWidgets.QWidget(self.widget_2)
        self.time_widget.setMinimumSize(QtCore.QSize(191, 108))
        self.time_widget.setMaximumSize(QtCore.QSize(191, 108))
        self.time_widget.setStyleSheet("QWidget#time_widget{\n"
"    background-color: rgb(3, 213, 255);\n"
"}\n"
"\n"
"QWidget#time_widget::hover{\n"
"    background-color: rgb(2, 192, 230);\n"
"}")
        self.time_widget.setObjectName("time_widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.time_widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_2 = QtWidgets.QLabel(self.time_widget)
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setMaximumSize(QtCore.QSize(50, 50))
        self.label_2.setStyleSheet("font: 20pt \"Segoe UI\";")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Graphics/graphics/connected_time.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.time_content = QtWidgets.QWidget(self.time_widget)
        self.time_content.setObjectName("time_content")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.time_content)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.time_percent = QtWidgets.QLabel(self.time_content)
        self.time_percent.setStyleSheet("font: bold 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);")
        self.time_percent.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_percent.setObjectName("time_percent")
        self.gridLayout_4.addWidget(self.time_percent, 3, 0, 1, 1)
        self.current_time = QtWidgets.QLabel(self.time_content)
        self.current_time.setStyleSheet("font: bold 16pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);")
        self.current_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.current_time.setObjectName("current_time")
        self.gridLayout_4.addWidget(self.current_time, 0, 0, 1, 1)
        self.elapsed_time = QtWidgets.QLabel(self.time_content)
        self.elapsed_time.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);")
        self.elapsed_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.elapsed_time.setObjectName("elapsed_time")
        self.gridLayout_4.addWidget(self.elapsed_time, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.time_content, 0, 1, 1, 1)
        self.time_progress = QtWidgets.QProgressBar(self.time_widget)
        self.time_progress.setMaximumSize(QtCore.QSize(16777215, 5))
        self.time_progress.setStyleSheet("QProgressBar {\n"
"    border: none;\n"
"    /*border-radius: 1px;\n"
"    text-align: center;*/\n"
"    background-color: rgb(0, 0, 0, 100);\n"
"    height:1px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border-radius: 0.5px;\n"
"    background-color: white;\n"
"}")
        self.time_progress.setProperty("value", 50)
        self.time_progress.setTextVisible(False)
        self.time_progress.setObjectName("time_progress")
        self.gridLayout_5.addWidget(self.time_progress, 1, 0, 1, 2)
        self.gridLayout_16.addWidget(self.time_widget, 0, 1, 1, 1)
        self.speed_widget = QtWidgets.QWidget(self.widget_2)
        self.speed_widget.setMinimumSize(QtCore.QSize(260, 108))
        self.speed_widget.setMaximumSize(QtCore.QSize(166662, 108))
        self.speed_widget.setStyleSheet("QWidget#speed_widget{\n"
"    background-color:rgb(255, 152, 166);\n"
"}\n"
"\n"
"QWidget#speed_widget::hover{\n"
"    background-color:rgb(232, 138, 152);\n"
"}")
        self.speed_widget.setObjectName("speed_widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.speed_widget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_5 = QtWidgets.QLabel(self.speed_widget)
        self.label_5.setMinimumSize(QtCore.QSize(50, 50))
        self.label_5.setMaximumSize(QtCore.QSize(50, 50))
        self.label_5.setStyleSheet("font: 20pt \"Segoe UI\";")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/Graphics/graphics/speed_flat.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.speed_widget)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.upload_speed = QtWidgets.QLabel(self.widget_6)
        self.upload_speed.setStyleSheet("font: bold 14pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);")
        self.upload_speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.upload_speed.setObjectName("upload_speed")
        self.gridLayout_7.addWidget(self.upload_speed, 0, 0, 1, 1)
        self.increase_u_speed = QtWidgets.QLabel(self.widget_6)
        self.increase_u_speed.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);")
        self.increase_u_speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.increase_u_speed.setObjectName("increase_u_speed")
        self.gridLayout_7.addWidget(self.increase_u_speed, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.download_speed = QtWidgets.QLabel(self.widget_6)
        self.download_speed.setStyleSheet("font: bold 14pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);")
        self.download_speed.setObjectName("download_speed")
        self.gridLayout_8.addWidget(self.download_speed, 0, 0, 1, 1)
        self.increase_d_speed = QtWidgets.QLabel(self.widget_6)
        self.increase_d_speed.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);")
        self.increase_d_speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.increase_d_speed.setObjectName("increase_d_speed")
        self.gridLayout_8.addWidget(self.increase_d_speed, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        self.gridLayout_10.addWidget(self.widget_6, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_5, 0, 1, 1, 1)
        self.gridLayout_16.addWidget(self.speed_widget, 0, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem5, 0, 2, 1, 1)
        self.gridLayout_12.addWidget(self.widget_2, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.status_container, 0, 0, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 841, 21))
        self.menubar.setObjectName("menubar")
        self.menuPrograma = QtWidgets.QMenu(self.menubar)
        self.menuPrograma.setObjectName("menuPrograma")
        self.menuHerramientas = QtWidgets.QMenu(self.menubar)
        self.menuHerramientas.setObjectName("menuHerramientas")
        self.menuAcerca_de = QtWidgets.QMenu(self.menubar)
        self.menuAcerca_de.setObjectName("menuAcerca_de")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.exit_action = QtWidgets.QAction(MainWindow)
        self.exit_action.setObjectName("exit_action")
        self.admin_users_action = QtWidgets.QAction(MainWindow)
        self.admin_users_action.setObjectName("admin_users_action")
        self.get_status_action = QtWidgets.QAction(MainWindow)
        self.get_status_action.setObjectName("get_status_action")
        self.actionDesarrollado_por_jalexbeats = QtWidgets.QAction(MainWindow)
        self.actionDesarrollado_por_jalexbeats.setObjectName("actionDesarrollado_por_jalexbeats")
        self.show_f_window = QtWidgets.QAction(MainWindow)
        self.show_f_window.setObjectName("show_f_window")
        self.menuPrograma.addAction(self.show_f_window)
        self.menuPrograma.addSeparator()
        self.menuPrograma.addAction(self.exit_action)
        self.menuHerramientas.addAction(self.admin_users_action)
        self.menuAcerca_de.addAction(self.actionDesarrollado_por_jalexbeats)
        self.menubar.addAction(self.menuPrograma.menuAction())
        self.menubar.addAction(self.menuHerramientas.menuAction())
        self.menubar.addAction(self.menuAcerca_de.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.exit_action.triggered.connect(MainWindow.close)
        self.ticket_rb.clicked['bool'].connect(self.password_ledit.setDisabled)
        self.permanent_rb.clicked['bool'].connect(self.password_ledit.setEnabled)
        self.close_pupup.clicked.connect(self.frame_error.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.user_ledit, self.password_ledit)
        MainWindow.setTabOrder(self.password_ledit, self.ticket_rb)
        MainWindow.setTabOrder(self.ticket_rb, self.permanent_rb)
        MainWindow.setTabOrder(self.permanent_rb, self.checkBox_save_user)
        MainWindow.setTabOrder(self.checkBox_save_user, self.login_btn)
        MainWindow.setTabOrder(self.login_btn, self.close_pupup)
        MainWindow.setTabOrder(self.close_pupup, self.table)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "X-GAMES"))
        self.label_error.setText(_translate("MainWindow", "Error"))
        self.user_ledit.setPlaceholderText(_translate("MainWindow", "USUARIO"))
        self.password_ledit.setPlaceholderText(_translate("MainWindow", "CONTRASEÑA"))
        self.checkBox_save_user.setText(_translate("MainWindow", "Guardar usuario"))
        self.permanent_rb.setText(_translate("MainWindow", "Fijo"))
        self.ticket_rb.setText(_translate("MainWindow", "Ticket"))
        self.login_btn.setText(_translate("MainWindow", "LOGIN"))
        item = self.table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tiempo del ticket"))
        item = self.table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Vence"))
        item = self.table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Consumo total"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Valor"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Restante"))
        __sortingEnabled = self.table.isSortingEnabled()
        self.table.setSortingEnabled(False)
        item = self.table.item(0, 0)
        item.setText(_translate("MainWindow", "00:00:00"))
        item = self.table.item(0, 1)
        item.setText(_translate("MainWindow", "00:00:00"))
        item = self.table.item(1, 0)
        item.setText(_translate("MainWindow", "1-8-2020 00:00:00"))
        item = self.table.item(1, 1)
        item.setText(_translate("MainWindow", "00:00:00"))
        item = self.table.item(2, 0)
        item.setText(_translate("MainWindow", "1-8-2020 00:00:00"))
        item = self.table.item(2, 1)
        item.setText(_translate("MainWindow", "00:00:00"))
        self.table.setSortingEnabled(__sortingEnabled)
        self.logout_btn.setText(_translate("MainWindow", "LOGOUT"))
        self.xgames_btn.setText(_translate("MainWindow", "..."))
        self.time_percent.setText(_translate("MainWindow", "0%"))
        self.current_time.setText(_translate("MainWindow", "00:00:00"))
        self.elapsed_time.setText(_translate("MainWindow", "00:00:00"))
        self.upload_speed.setText(_translate("MainWindow", "↑ 175.0 KiB"))
        self.increase_u_speed.setText(_translate("MainWindow", "+0 B"))
        self.download_speed.setText(_translate("MainWindow", "↓ 175.0 KiB"))
        self.increase_d_speed.setText(_translate("MainWindow", "+0 B"))
        self.menuPrograma.setTitle(_translate("MainWindow", "Programa"))
        self.menuHerramientas.setTitle(_translate("MainWindow", "Herramientas"))
        self.menuAcerca_de.setTitle(_translate("MainWindow", "Acerca de"))
        self.exit_action.setText(_translate("MainWindow", "Salir"))
        self.admin_users_action.setText(_translate("MainWindow", "Administrar usuarios"))
        self.get_status_action.setText(_translate("MainWindow", "Obtener estado"))
        self.actionDesarrollado_por_jalexbeats.setText(_translate("MainWindow", "Desarrollado por @jalexbeats"))
        self.show_f_window.setText(_translate("MainWindow", "Ver ventana de estado"))
import file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
